import type { Metadata } from "next";

import { PageHeading } from "@/components/page-heading";
import { getSiteSettings } from "@/lib/data/public";

export const metadata: Metadata = { title: "Privacy", description: "How Afgekia handles booking and client information." };

export default async function PrivacyPage() {
  const settings = await getSiteSettings();
  return <article className="container-shell py-18 sm:py-24"><PageHeading eyebrow="Privacy" title="Your information is handled with care." description="This notice explains the information Afgekia collects through this website and how it is used." /><div className="prose-afgekia mt-14 max-w-3xl"><h2>Client registration</h2><p>Registration collects your name, email, timezone, and consent record. Your account remains pending until an administrator activates it. Administrators manage account access but cannot read private project or booking contents.</p><h2>Listing project requests</h2><p>Signed-in clients choose a listed project owner and provide a short property address, seller nickname, summary, and optional details. Only the selected owner and the requesting client can read that request. An approved request becomes a private project and the requester becomes its first client member.</p><h2>Booking requests</h2><p>Booking is separate from project intake. We collect the selected owner and appointment type, contact details, preferred times, timezone, and message so that the selected owner can respond and maintain the appointment record.</p><h2>Private project records</h2><p>Project stages, milestones, approvals, updates, and AI-assisted summaries are available only according to account role, project ownership, and project membership. Afgekia does not sell personal information or publish private project data.</p><h2>Retention and security</h2><p>Information is retained while useful for the working relationship, legal obligations, and ordinary business records. Access is restricted in the database as well as the application. No online system can promise absolute security, but practical technical and organizational controls are applied.</p><h2>Your questions</h2><p>To ask about, correct, or request deletion of your personal information, email <a href={`mailto:${settings.contact_email}`}>{settings.contact_email}</a>.</p><p className="text-sm text-muted-foreground">Last updated August 25, 2026.</p></div></article>;
}
