import { ArrowRight, CheckCircle2 } from "lucide-react";
import Link from "next/link";

import { ArticleCard } from "@/components/article-card";
import { PortfolioCard } from "@/components/portfolio-card";
import { Button } from "@/components/ui/button";
import { getArticles, getPortfolio, getServices, getSiteSettings } from "@/lib/data/public";

export default async function HomePage() {
  const [settings, services, portfolio, articles] = await Promise.all([getSiteSettings(), getServices(), getPortfolio(), getArticles()]);
  return (
    <>
      <section className="container-shell grid min-h-[76vh] items-center gap-12 py-20 lg:grid-cols-[1.2fr_.8fr] lg:py-28">
        <div><p className="eyebrow">Business assistance · Project support</p><h1 className="mt-5 max-w-4xl text-balance text-6xl leading-[.92] tracking-[-0.045em] sm:text-7xl lg:text-[6rem]">Less scramble.<br /><em className="font-normal text-primary">More useful progress.</em></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">{settings.description}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-11 px-5"><Link href="/book">Tell me what needs moving <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="h-11 px-5"><Link href="/work">See recent work</Link></Button></div></div>
        <aside className="relative mx-auto w-full max-w-md rounded-[2rem] border bg-card p-7 shadow-[0_30px_80px_-50px_rgba(45,51,30,.55)] sm:p-9"><div aria-hidden="true" className="absolute -top-7 -right-6 size-20 rounded-full bg-terracotta/25 blur-xl" /><p className="font-heading text-2xl">A steadier working rhythm</p><div className="mt-7 space-y-5">{["Priorities that fit the real week", "Project updates people can use", "Follow-through without constant chasing"].map((item) => <div key={item} className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-primary" /><p className="text-sm leading-6">{item}</p></div>)}</div><div className="mt-8 border-t pt-6"><p className="text-xs font-semibold tracking-wider text-muted-foreground uppercase">Current availability</p><p className="mt-2 text-sm">Accepting selected September projects</p></div></aside>
      </section>
      <section className="border-y bg-card/65 py-20 sm:py-28"><div className="container-shell"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">How I can help</p><h2 className="mt-4 text-5xl leading-none">Clear support,<br />shaped to the work.</h2><Button asChild variant="link" className="mt-6 px-0"><Link href="/services">Explore all services <ArrowRight /></Link></Button></div><div className="grid gap-4 sm:grid-cols-2">{services.map((service, index) => <div key={service.id} className="rounded-2xl border bg-background/70 p-6"><span className="font-heading text-3xl text-terracotta/70">0{index + 1}</span><h3 className="mt-7 text-2xl">{service.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{service.description}</p></div>)}</div></div></div></section>
      <section className="container-shell py-20 sm:py-28"><div className="mb-12 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Selected work</p><h2 className="mt-4 text-5xl">Progress, made visible.</h2></div><Button asChild variant="outline"><Link href="/work">View all work <ArrowRight /></Link></Button></div><div className="grid gap-5 md:grid-cols-2">{portfolio.slice(0, 3).map((item, index) => <PortfolioCard key={item.id} item={item} priority={index === 0} />)}</div></section>
      <section className="container-shell py-16"><div className="mb-9"><p className="eyebrow">Notes from the work</p><h2 className="mt-4 text-5xl">Useful thinking, simply shared.</h2></div>{articles.slice(0, 3).map((article) => <ArticleCard key={article.id} article={article} />)}</section>
      <section className="container-shell py-16"><div className="rounded-[2rem] bg-primary px-7 py-14 text-center text-primary-foreground sm:px-12 sm:py-20"><p className="text-xs font-semibold tracking-[.18em] uppercase text-primary-foreground/70">Start a conversation</p><h2 className="mx-auto mt-5 max-w-3xl text-balance text-5xl leading-none sm:text-6xl">What would feel lighter with the right support?</h2><p className="mx-auto mt-6 max-w-xl leading-7 text-primary-foreground/75">Share the shape of the work. You’ll receive a personal reply, not an automated calendar confirmation.</p><Button asChild size="lg" variant="secondary" className="mt-8 h-11"><Link href="/book">Request a conversation <ArrowRight /></Link></Button></div></section>
    </>
  );
}
